export const IMAGES = {
    
    user : require('../assets/images/user.png'),
    card : require('../assets/images/card.png'),
    card1 : require('../assets/images/card1.png'),
    Vector : require('../assets/images/Vector.png'),
    cardbackground1 : require('../assets/images/cardbackground1.png'),
    cardbackground2 : require('../assets/images/cardbackground2.png'),
    appname : require('../assets/images/appname.png'),
    appname2 : require('../assets/images/appname2.png'),
    appnamedark : require('../assets/images/appname-dark.png'),
    appVacaLogoHorizontal : require('../assets/images/HorizontalGanado.png'),

    headerlogo : require('../assets/images/headerlogo.png'),
    google2 : require('../assets/images/icons/google2.png'),
    facebook : require('../assets/images/icons/facebook.png'),
    Home: require('../assets/images/icons/home.png'),
    Home4: require('../assets/images/icons/home4.png'),
    heart: require('../assets/images/icons/heart.png'),
    mycart: require('../assets/images/icons/shopping2.png'),
    Category: require('../assets/images/icons/document.png'),
    user2: require('../assets/images/icons/user.png'),
    user3: require('../assets/images/icons/user4.png'),
    grid3: require('../assets/images/icons/grid3.png'),
    grid4: require('../assets/images/icons/grid4.png'),
    grid5: require('../assets/images/icons/grid5.png'),
    grid6: require('../assets/images/icons/grid6.png'),
    shose: require('../assets/images/icons/shose.png'),
    ball: require('../assets/images/icons/bell2.png'),
    ball2: require('../assets/images/icons/bell.png'),
    close: require('../assets/images/icons/close.png'),
    check: require('../assets/images/icons/check.png'),
    check2: require('../assets/images/icons/check2.png'),
    check3: require('../assets/images/icons/check3.png'),
    check4: require('../assets/images/icons/check4.png'),
    delete: require('../assets/images/icons/delete.png'),
    Chat: require('../assets/images/icons/Chat.png'),
    Star: require('../assets/images/icons/Star.png'),
    Star4: require('../assets/images/icons/star4.png'),
    wallet: require('../assets/images/icons/wallet.png'),
    wallet2: require('../assets/images/icons/wallet2.png'),
    Location: require('../assets/images/icons/Location.png'),
    Filter: require('../assets/images/icons/Filter.png'),
    Notification: require('../assets/images/icons/Notification.png'),
    search: require('../assets/images/icons/search.png'),
    list: require('../assets/images/icons/list.png'),
    list2: require('../assets/images/icons/list2.png'),
    grid: require('../assets/images/icons/grid.png'),
    arrowup: require('../assets/images/icons/arrowup.png'),
    filter2: require('../assets/images/icons/filter2.png'),
    filter3: require('../assets/images/icons/filter3.png'),
    shop: require('../assets/images/icons/shop.png'),
    Bag: require('../assets/images/icons/Bag.png'),
    plus: require('../assets/images/icons/plus.png'),
    dollar: require('../assets/images/icons/dollar.png'),
    payment: require('../assets/images/icons/payment.png'),
    folder: require('../assets/images/icons/folder.png'),
    bank: require('../assets/images/icons/bank.png'),
    shieldcheck: require('../assets/images/icons/shieldcheck.png'),
    card2: require('../assets/images/icons/card2.png'),
    write: require('../assets/images/icons/write.png'),
    downaeeowsmall: require('../assets/images/icons/downaeeowsmall.png'),
    home: require('../assets/images/icons/home4.png'),
    producta: require('../assets/images/icons/producta.png'),
    components: require('../assets/images/icons/components.png'),
    star: require('../assets/images/icons/star2.png'), 
    heart2: require('../assets/images/icons/heart2.png'), 
    order: require('../assets/images/icons/order.png'), 
    shopping: require('../assets/images/icons/shopping3.png'), 
    chat: require('../assets/images/icons/chat2.png'), 
    logout: require('../assets/images/icons/logout.png'), 
    call: require('../assets/images/icons/call.png'), 
    happy: require('../assets/images/icons/happy.png'), 
    send: require('../assets/images/icons/send.png'), 
    volume: require('../assets/images/icons/volume.png'), 
    phone: require('../assets/images/icons/phone.png'), 
    audio: require('../assets/images/icons/audio.png'), 
    audiomute: require('../assets/images/icons/audiomute.png'), 
    sun: require('../assets/images/icons/sun.png'), 
    darkMode: require('../assets/images/icons/moon.png'), 
    fire: require('../assets/images/icons/fire.png'), 
    deliverytruck: require('../assets/images/icons/delivery-truck.png'), 
    deliverytruck2: require('../assets/images/icons/delivery-truck2.png'), 
    savemoney: require('../assets/images/icons/save-money.png'), 
    technicalsupport: require('../assets/images/icons/technical-support.png'), 
    timer: require('../assets/images/icons/timer.png'), 
    offer: require('../assets/images/icons/offer.png'), 
    gift: require('../assets/images/icons/gift1.png'), 
    background: require('../assets/images/icons/background.png'), 
    star7: require('../assets/images/icons/star7.png'), 
    star8: require('../assets/images/icons/star8.png'), 
    leftarrow: require('../assets/images/icons/leftarrow.png'), 
    map: require('../assets/images/icons/map.png'), 
    savecheck: require('../assets/images/icons/save-check.png'), 
    translation: require('../assets/images/icons/translation.png'), 
    transfer: require('../assets/images/icons/transfer.png'), 
    shoppingbag: require('../assets/images/icons/shoppingbag.png'), 
    mobilenotch: require('../assets/images/icons/mobile-notch.png'), 
    marketplacestore: require('../assets/images/icons/marketplace-store.png'), 
    laptopmobile: require('../assets/images/icons/laptop-mobile.png'), 
    gamepad: require('../assets/images/icons/gamepad.png'), 
    couch: require('../assets/images/icons/couch.png'), 
    cameraretro: require('../assets/images/icons/camera-retro.png'), 
    qrscan: require('../assets/images/icons/qr-scan.png'), 
    airfreshener: require('../assets/images/icons/air-freshener.png'), 
    fashion: require('../assets/images/icons/fashion.png'), 
    email: require('../assets/images/icons/email.png'), 
    email2: require('../assets/images/icons/email2.png'), 
    lock: require('../assets/images/icons/lock.png'), 
    bolt: require('../assets/images/icons/bolt.png'), 
    biking: require('../assets/images/icons/biking.png'), 
    tachometerfast: require('../assets/images/icons/tachometer-fast.png'), 
    scale: require('../assets/images/icons/scale.png'), 
    truckcheck: require('../assets/images/icons/truck-check.png'), 
    Phoneduotone: require('../assets/images/icons/Phone_duotone.png'), 
    Pinduotone: require('../assets/images/icons/Pin_duotone.png'), 
    hamburger: require('../assets/images/icons/hamburger.png'), 
    cup: require('../assets/images/icons/cup.png'), 
    share: require('../assets/images/icons/share1.png'), 
    information: require('../assets/images/icons/information.png'), 

    welcome : require('../assets/images/onbording/welcome.png'),
    welcome2 : require('../assets/images/onbording/welcome2.png'),

    onborder3 : require('../assets/images/onbording/pic8.png'),
    onborder4 : require('../assets/images/onbording/pic9.png'),
    onborder5 : require('../assets/images/onbording/pic10.png'),

    vacaCategories :  require('../assets/images/icons/iconvaca.png'),

    vacasBording1 : require('../assets/images/bordingVacas/vaca1.png'),
    vacasBording2 : require('../assets/images/bordingVacas/vaca2.png'),
    vacasCards1 : require('../assets/images/bordingVacas/vaquitaCards1.png'),
    vacasCards2 : require('../assets/images/bordingVacas/vaquitaCards2.png'),
    cerdoCards1 : require('../assets/images/bordingVacas/cerdoCards1.png'),

    welcomeVacas: require('../assets/images/onbording/welcomeVacas.png'),

    item1: require('../assets/images/item/pic1.png'),
    item2: require('../assets/images/item/pic2.png'),
    item3: require('../assets/images/item/pic3.png'),
    item11: require('../assets/images/item/pic4.png'),
    item12: require('../assets/images/item/pic5.png'),
    item13: require('../assets/images/item/pic6.png'),
    item14: require('../assets/images/item/pic7.png'),
    item15: require('../assets/images/item/pic8.png'),
    item16: require('../assets/images/item/pic9.png'),
    

    item4: require('../assets/images/item2/pic1.png'),
    item5: require('../assets/images/item2/pic2.png'),
    item6: require('../assets/images/item2/pic3.png'),
   

    brand1: require('../assets/images/brand/pic1.png'),
    brand2: require('../assets/images/brand/pic2.png'),
    brand3: require('../assets/images/brand/pic3.png'),
    brand4: require('../assets/images/brand/pic4.png'),
    brand5: require('../assets/images/brand/pic5.png'),
    brand6: require('../assets/images/brand/pic6.png'),
    brand7: require('../assets/images/brand/pic7.png'),
    brand8: require('../assets/images/brand/pic8.png'),
    brand9: require('../assets/images/brand/pic9.png'),
    brand10: require('../assets/images/brand/pic10.png'),
    brand11: require('../assets/images/brand/pic11.png'),
    brand12: require('../assets/images/brand/pic12.png'),
    brand13: require('../assets/images/brand/pic13.png'),
    brand14: require('../assets/images/brand/pic14.png'),
    brand15: require('../assets/images/brand/pic15.png'),
    brand16: require('../assets/images/brand/pic16.png'),
    brand17: require('../assets/images/brand/pic17.png'),


    small1: require('../assets/images/small/pic5.png'),
    small2: require('../assets/images/small/pic6.png'),
    small3: require('../assets/images/small/pic7.png'),
    small4: require('../assets/images/small/pic8.png'),
    small5: require('../assets/images/small/pic9.png'),
    small6: require('../assets/images/small/pic10.png'),
    small7: require('../assets/images/small/pic11.png'),

    flags1: require('../assets/images/flags/pic1.png'),
    flags2: require('../assets/images/flags/pic2.png'),
    flags3: require('../assets/images/flags/pic3.png'),
    flags4: require('../assets/images/flags/pic4.png'),
    flags5: require('../assets/images/flags/pic5.png'),
    flags6: require('../assets/images/flags/pic6.png'),
    flags7: require('../assets/images/flags/pic7.png'),
    flags8: require('../assets/images/flags/pic8.png'),
    flags9: require('../assets/images/flags/pic9.png'),
    flags10: require('../assets/images/flags/pic10.png'),
    flags11: require('../assets/images/flags/pic11.png'),
    flags12: require('../assets/images/flags/pic12.png'),
    flags13: require('../assets/images/flags/pic13.png'),
    flags14: require('../assets/images/flags/pic14.png'),

}