# Generated by Django 5.1.2 on 2024-10-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_titulo_cow_breed_cow_age_cow_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cow",
            name="breed",
        ),
    ]
